version: '3.5'

services:
  {{ (ds "config").DNS_PREFIX | strings.ReplaceAll "." "-" }}-{{ (ds "config").DNS_SUFFIX | strings.ReplaceAll "." "-" }}:
    image: ${DOCKER_REGISTRY}{{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}:${BRANCH:-develop}.${VERSION:-local}-build
    build:
      target: build
    volumes:
      - app:/var/release/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-app-extract-publish}