version: '3.5'

services:
  {{ (ds "config").DNS_PREFIX | strings.ReplaceAll "." "-" }}-{{ (ds "config").DNS_SUFFIX | strings.ReplaceAll "." "-" }}:
    image: ${DOCKER_REGISTRY}{{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}:${BRANCH}.${VERSION}
    ports:
      - "5432:5432"
    env_file: env-stable.env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: {{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}

networks:
  default:
    name: ns-{{ (ds "config").SOFTWARE_NAME }}
