version: '3.5'

services:
  {{ (ds "config").DNS_PREFIX | strings.ReplaceAll "." "-" }}-{{ (ds "config").DNS_SUFFIX | strings.ReplaceAll "." "-" }}:
    image: ${DOCKER_REGISTRY}{{ (ds "config").DNS_PREFIX }}.{{ (ds "config").DNS_SUFFIX }}:${BRANCH:-develop}.${VERSION:-local}
    container_name: {{ (ds "config").DNS_PREFIX }}-local.{{ (ds "config").DNS_SUFFIX }}
    build:
      target: deploy
      context: .
      dockerfile: Software/Dockerfile
